name: learn-github-actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - id: find-md
        run: echo "::set-output name=find::$(find -name *.md)"
        shell: bash
      - run: echo ${{ steps.find-md.outputs.find }}
